#!/bin/bash -
#==============================================================================
#
#       FILE: authnyc
# 
#      USAGE: source authnyc
#             start_authnyc
#             stop_authnyc
#
# DESCRIPTION: Bash start and stop script for Authnyc!
#
#
# AUTHOR: Michael Konrad (Copyright 2024)
#
# CREATED: 2024-08-30
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#==============================================================================

set -o nounset
IFS=$'\n\t'

SA_HOME=$(pwd)

start_authnyc() {
        . $SA_HOME/venv/bin/activate
        streamlit run $SA_HOME/src/authnyc/authnyc.py &
}

stop_authnyc() {
        PID=$(jobs -l | grep streamlit | cut -d ' ' -f 2)
        kill $PID
        deactivate
}