[config]
oidc_provider_configured = true

[oidc_providers]
'Select a provider' = 'select_provider'
'Auth0' = 'auth0'

[oidc_api_providers]
'Select a resource' = 'select_resource'
'Auth0 API' = 'auth0_api'            